name: Robby_Locks
services:
  - name: web
    environment_slug: python
    github:
      repo: ntschetterNY/Robby_Locks
      branch: main
    run_command: gunicorn --bind 0.0.0.0:8080 app:app
    http_port: 8080
    instance_count: 1
    environment_variables:
      FLASK_ENV: production
      # Add any additional environment variables below as needed
      # For example:
      # SECRET_KEY: "your-secret-key"
